### ISSUE TITLE
Full Screen Modal can't close

### ISSUE THREAD

**Issue by phuoctaiismee** [Asfak00/zenui-library#51] opened 2024-11-19 04:49 UTC
In the full-screen modal section, please add a modal close button or for the keyboard event on the ESC

**Comment by eshward95** [comment] 2024-11-20 08:55
@Asfak00 Can you assign this issue to me I am working on this.

**Comment by Asfak00** [comment] 2024-11-20 10:30
> @Asfak00 Can you assign this issue to me I am working on this.

I saw the issue. I think you just increase the modal z-index. The modal have close icon for close the modal and it hide now because the ZenUI main navbar upper in the modal that's why. So you just increase the modal z-index I hope the problem is solved.

**Closed as completed** 2024-11-21 06:56 UTC
